{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "af73ac02",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting lightgbm\n",
      "  Downloading lightgbm-4.6.0-py3-none-manylinux_2_28_x86_64.whl.metadata (17 kB)\n",
      "Requirement already satisfied: numpy>=1.17.0 in /home/codespace/.local/lib/python3.12/site-packages (from lightgbm) (2.3.1)\n",
      "Requirement already satisfied: scipy in /home/codespace/.local/lib/python3.12/site-packages (from lightgbm) (1.16.0)\n",
      "Downloading lightgbm-4.6.0-py3-none-manylinux_2_28_x86_64.whl (3.6 MB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m3.6/3.6 MB\u001b[0m \u001b[31m9.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hInstalling collected packages: lightgbm\n",
      "Successfully installed lightgbm-4.6.0\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m25.1.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m25.2\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpython -m pip install --upgrade pip\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install lightgbm\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from lightgbm import LGBMClassifier\n",
    "from sklearn.metrics import accuracy_score, classification_report, confusion_matrix\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "009eb93a",
   "metadata": {},
   "outputs": [],
   "source": [
    "train_df = pd.read_csv('/home/codespace/.jupyter/NeurIPS/Data/train.csv')\n",
    "ts = pd.read_csv('/home/codespace/.jupyter/NeurIPS/Data/test.csv')\n",
    "ss = pd.read_csv('/home/codespace/.jupyter/NeurIPS/Data/sample_submission.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "d0989cd6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Total rows:   7973\n",
      "Dev train:    4783 (59.99%)\n",
      "Dev valid:    1595 (20.01%)\n",
      "Dev test:     1595 (20.01%)\n",
      "Polymer example:['*Nc1ccc(CC(CC(C)(C)c2ccc(N*)cc2)=C(C)C)cc1', '*CC(*)(CC(=O)OC)C(=O)OC12CC3CC(C)(CC(C)(C3)C1)C2', '*OP(=O)(Oc1c(Cl)cc(Cl)cc1Cl)Oc1c(Cl)c(Cl)c(*)c(Cl)c1Cl']\n",
      "Columns:Index(['id', 'SMILES', 'Tg', 'FFV', 'Tc', 'Density', 'Rg'], dtype='object')\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "\n",
    "# 1. split off 20% for dev_test\n",
    "temp_df, dev_test = train_test_split(\n",
    "    train_df,\n",
    "    test_size=0.2,\n",
    "    random_state=42,  # for reproducibility\n",
    "    shuffle=True\n",
    ")\n",
    "\n",
    "# 2. split the remaining 80% into 75% train / 25% valid → 0.6 / 0.2 overall\n",
    "dev_train, dev_val = train_test_split(\n",
    "    temp_df,\n",
    "    test_size=0.25,  # 0.25 * 0.8 = 0.2 of the original\n",
    "    random_state=42,\n",
    "    shuffle=True\n",
    ")\n",
    "\n",
    "# Verify sizes\n",
    "print(f\"Total rows:   {len(train_df)}\")\n",
    "print(f\"Dev train:    {len(dev_train)} ({len(dev_train)/len(train_df):.2%})\")\n",
    "print(f\"Dev valid:    {len(dev_val)} ({len(dev_val)/len(train_df):.2%})\")\n",
    "print(f\"Dev test:     {len(dev_test)} ({len(dev_test)/len(train_df):.2%})\")\n",
    "print(f\"Polymer example:{dev_train['SMILES'].to_list()[:3]}\")\n",
    "print(f\"Columns:{dev_train.columns}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "5c86eade",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "char_dic = {\n",
    "    '<pad>': 0,\n",
    "    '#': 1,   # Triple bond\n",
    "    '%': 2,   # Two-digit ring closure (e.g., '%10')\n",
    "    '(': 3,   # Branch opening\n",
    "    ')': 4,   # Branch closing\n",
    "    '*': 5,   # Wildcard atom (used in BigSMILES for polymer repeating units)\n",
    "    '+': 6,   # Positive charge\n",
    "    '-': 7,   # Negative charge\n",
    "    '0': 8,   # Ring closure digit\n",
    "    '1': 9,\n",
    "    '2': 10,\n",
    "    '3': 11,\n",
    "    '4': 12,\n",
    "    '5': 13,\n",
    "    '6': 14,\n",
    "    '7': 15,\n",
    "    '8': 16,\n",
    "    '9': 17,\n",
    "    '.': 18,  # Disconnected structures\n",
    "    '/': 19,  # Stereochemistry (up bond)\n",
    "    '1': 20,  # Stereochemistry (down bond)\n",
    "    'A': 21\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "f9cd924a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: torch_molecule in /usr/local/python/3.12.1/lib/python3.12/site-packages (0.1.3)\n",
      "Requirement already satisfied: tqdm in /usr/local/python/3.12.1/lib/python3.12/site-packages (4.67.1)\n",
      "Requirement already satisfied: torch>=2.2.0 in /home/codespace/.local/lib/python3.12/site-packages (from torch_molecule) (2.7.1+cpu)\n",
      "Requirement already satisfied: torch-geometric>=2.6.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from torch_molecule) (2.6.1)\n",
      "Requirement already satisfied: numpy in /home/codespace/.local/lib/python3.12/site-packages (from torch_molecule) (2.3.1)\n",
      "Requirement already satisfied: huggingface_hub>=0.22.2 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from torch_molecule) (0.34.4)\n",
      "Requirement already satisfied: joblib>=1.3.2 in /home/codespace/.local/lib/python3.12/site-packages (from torch_molecule) (1.5.1)\n",
      "Requirement already satisfied: networkx>=3.2.1 in /home/codespace/.local/lib/python3.12/site-packages (from torch_molecule) (3.3)\n",
      "Requirement already satisfied: rdkit>=2023.9.5 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from torch_molecule) (2025.3.6)\n",
      "Requirement already satisfied: scikit_learn>=1.2.2 in /home/codespace/.local/lib/python3.12/site-packages (from torch_molecule) (1.7.0)\n",
      "Requirement already satisfied: scipy>=1.14.1 in /home/codespace/.local/lib/python3.12/site-packages (from torch_molecule) (1.16.0)\n",
      "Requirement already satisfied: optuna>=4.0.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from torch_molecule) (4.5.0)\n",
      "Requirement already satisfied: filelock in /home/codespace/.local/lib/python3.12/site-packages (from huggingface_hub>=0.22.2->torch_molecule) (3.13.1)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in /home/codespace/.local/lib/python3.12/site-packages (from huggingface_hub>=0.22.2->torch_molecule) (2024.6.1)\n",
      "Requirement already satisfied: packaging>=20.9 in /home/codespace/.local/lib/python3.12/site-packages (from huggingface_hub>=0.22.2->torch_molecule) (25.0)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /home/codespace/.local/lib/python3.12/site-packages (from huggingface_hub>=0.22.2->torch_molecule) (6.0.2)\n",
      "Requirement already satisfied: requests in /home/codespace/.local/lib/python3.12/site-packages (from huggingface_hub>=0.22.2->torch_molecule) (2.32.4)\n",
      "Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/codespace/.local/lib/python3.12/site-packages (from huggingface_hub>=0.22.2->torch_molecule) (4.14.1)\n",
      "Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from huggingface_hub>=0.22.2->torch_molecule) (1.1.10)\n",
      "Requirement already satisfied: alembic>=1.5.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from optuna>=4.0.0->torch_molecule) (1.16.5)\n",
      "Requirement already satisfied: colorlog in /usr/local/python/3.12.1/lib/python3.12/site-packages (from optuna>=4.0.0->torch_molecule) (6.9.0)\n",
      "Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from optuna>=4.0.0->torch_molecule) (2.0.43)\n",
      "Requirement already satisfied: Mako in /usr/local/python/3.12.1/lib/python3.12/site-packages (from alembic>=1.5.0->optuna>=4.0.0->torch_molecule) (1.3.10)\n",
      "Requirement already satisfied: Pillow in /home/codespace/.local/lib/python3.12/site-packages (from rdkit>=2023.9.5->torch_molecule) (11.3.0)\n",
      "Requirement already satisfied: threadpoolctl>=3.1.0 in /home/codespace/.local/lib/python3.12/site-packages (from scikit_learn>=1.2.2->torch_molecule) (3.6.0)\n",
      "Requirement already satisfied: greenlet>=1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from sqlalchemy>=1.4.2->optuna>=4.0.0->torch_molecule) (3.2.4)\n",
      "Requirement already satisfied: setuptools in /home/codespace/.local/lib/python3.12/site-packages (from torch>=2.2.0->torch_molecule) (80.9.0)\n",
      "Requirement already satisfied: sympy>=1.13.3 in /home/codespace/.local/lib/python3.12/site-packages (from torch>=2.2.0->torch_molecule) (1.13.3)\n",
      "Requirement already satisfied: jinja2 in /home/codespace/.local/lib/python3.12/site-packages (from torch>=2.2.0->torch_molecule) (3.1.6)\n",
      "Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/codespace/.local/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=2.2.0->torch_molecule) (1.3.0)\n",
      "Requirement already satisfied: aiohttp in /usr/local/python/3.12.1/lib/python3.12/site-packages (from torch-geometric>=2.6.1->torch_molecule) (3.12.15)\n",
      "Requirement already satisfied: psutil>=5.8.0 in /home/codespace/.local/lib/python3.12/site-packages (from torch-geometric>=2.6.1->torch_molecule) (7.0.0)\n",
      "Requirement already satisfied: pyparsing in /home/codespace/.local/lib/python3.12/site-packages (from torch-geometric>=2.6.1->torch_molecule) (3.2.3)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from aiohttp->torch-geometric>=2.6.1->torch_molecule) (2.6.1)\n",
      "Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from aiohttp->torch-geometric>=2.6.1->torch_molecule) (1.4.0)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /home/codespace/.local/lib/python3.12/site-packages (from aiohttp->torch-geometric>=2.6.1->torch_molecule) (25.3.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from aiohttp->torch-geometric>=2.6.1->torch_molecule) (1.7.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from aiohttp->torch-geometric>=2.6.1->torch_molecule) (6.6.4)\n",
      "Requirement already satisfied: propcache>=0.2.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from aiohttp->torch-geometric>=2.6.1->torch_molecule) (0.3.2)\n",
      "Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from aiohttp->torch-geometric>=2.6.1->torch_molecule) (1.20.1)\n",
      "Requirement already satisfied: idna>=2.0 in /home/codespace/.local/lib/python3.12/site-packages (from yarl<2.0,>=1.17.0->aiohttp->torch-geometric>=2.6.1->torch_molecule) (3.10)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /home/codespace/.local/lib/python3.12/site-packages (from jinja2->torch>=2.2.0->torch_molecule) (3.0.2)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in /home/codespace/.local/lib/python3.12/site-packages (from requests->huggingface_hub>=0.22.2->torch_molecule) (3.4.2)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codespace/.local/lib/python3.12/site-packages (from requests->huggingface_hub>=0.22.2->torch_molecule) (2.5.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /home/codespace/.local/lib/python3.12/site-packages (from requests->huggingface_hub>=0.22.2->torch_molecule) (2025.7.9)\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m25.1.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m25.2\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpython -m pip install --upgrade pip\u001b[0m\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[I 2025-09-12 23:45:23,598] A new study created in memory with name: LSTMMolecularPredictor_optimization\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Model initialized successfully\n",
      "\n",
      "Parameter Search Configuration:\n",
      "--------------------------------------------------\n",
      "\n",
      " Parameters being searched:\n",
      "  • LSTMunits: [30, 120]\n",
      "  • learning_rate: [0.0001, 0.01]\n",
      "  • output_dim: [8, 32]\n",
      "\n",
      " Fixed parameters (not being searched):\n",
      "  • batch_size: 192\n",
      "  • device: cpu\n",
      "  • epochs: 200\n",
      "  • evaluate_criterion: <function mean_absolute_error at 0x7c4277d6d800>\n",
      "  • evaluate_higher_better: False\n",
      "  • evaluate_name: mae\n",
      "  • fitting_epoch: 0\n",
      "  • fitting_loss: []\n",
      "  • input_dim: 54\n",
      "  • loss_criterion: MSELoss()\n",
      "  • max_input_len: 200\n",
      "  • num_task: 5\n",
      "  • patience: 50\n",
      "  • scheduler_factor: 0.5\n",
      "  • scheduler_patience: 5\n",
      "  • task_type: regression\n",
      "  • use_lr_scheduler: False\n",
      "  • verbose: True\n",
      "  • weight_decay: 0.0\n",
      "\n",
      "--------------------------------------------------\n",
      "\n",
      "Starting hyperparameter optimization using mae metric\n",
      "Direction: minimize\n",
      "Number of trials: 10\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---                 \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 24, in emit\n",
      "    tqdm.write(msg)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 720, in write\n",
      "    with cls.external_write_mode(file=file, nolock=nolock):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/contextlib.py\", line 144, in __exit__\n",
      "    next(self.gen)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 750, in external_write_mode\n",
      "    inst.refresh(nolock=True)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1347, in refresh\n",
      "    self.display()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 156, in display\n",
      "    ltext, pbar, rtext = self.container.children\n",
      "                         ^^^^^^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'container'\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1849/362209100.py\", line 40, in <module>\n",
      "    lstm.autofit(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 351, in autofit\n",
      "    study.optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/study.py\", line 490, in optimize\n",
      "    _optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 63, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 160, in _optimize_sequential\n",
      "    frozen_trial_id = _run_trial(study, func, catch)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 234, in _run_trial\n",
      "    _log_failed_trial(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 269, in _log_failed_trial\n",
      "    _logger.warning(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1551, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 29, in emit\n",
      "    self.handleError(record)\n",
      "Message: \"Trial 0 failed with parameters: {'output_dim': 29, 'LSTMunits': 42, 'learning_rate': 0.0003796094420115622} because of the following error: ImportError('IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html').\"\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 24, in emit\n",
      "    tqdm.write(msg)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 720, in write\n",
      "    with cls.external_write_mode(file=file, nolock=nolock):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/contextlib.py\", line 144, in __exit__\n",
      "    next(self.gen)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 750, in external_write_mode\n",
      "    inst.refresh(nolock=True)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1347, in refresh\n",
      "    self.display()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 156, in display\n",
      "    ltext, pbar, rtext = self.container.children\n",
      "                         ^^^^^^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'container'\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1849/362209100.py\", line 40, in <module>\n",
      "    lstm.autofit(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 351, in autofit\n",
      "    study.optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/study.py\", line 490, in optimize\n",
      "    _optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 63, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 160, in _optimize_sequential\n",
      "    frozen_trial_id = _run_trial(study, func, catch)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 234, in _run_trial\n",
      "    _log_failed_trial(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 276, in _log_failed_trial\n",
      "    _logger.warning(\"Trial {} failed with value {}.\".format(trial_number, repr(value_or_values)))\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1551, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 29, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Trial 0 failed with value None.'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 24, in emit\n",
      "    tqdm.write(msg)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 720, in write\n",
      "    with cls.external_write_mode(file=file, nolock=nolock):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/contextlib.py\", line 144, in __exit__\n",
      "    next(self.gen)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 750, in external_write_mode\n",
      "    inst.refresh(nolock=True)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1347, in refresh\n",
      "    self.display()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 156, in display\n",
      "    ltext, pbar, rtext = self.container.children\n",
      "                         ^^^^^^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'container'\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1849/362209100.py\", line 40, in <module>\n",
      "    lstm.autofit(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 351, in autofit\n",
      "    study.optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/study.py\", line 490, in optimize\n",
      "    _optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 63, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 160, in _optimize_sequential\n",
      "    frozen_trial_id = _run_trial(study, func, catch)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 234, in _run_trial\n",
      "    _log_failed_trial(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 269, in _log_failed_trial\n",
      "    _logger.warning(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1551, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 29, in emit\n",
      "    self.handleError(record)\n",
      "Message: \"Trial 1 failed with parameters: {'output_dim': 15, 'LSTMunits': 39, 'learning_rate': 0.0010747128665878412} because of the following error: ImportError('IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html').\"\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 24, in emit\n",
      "    tqdm.write(msg)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 720, in write\n",
      "    with cls.external_write_mode(file=file, nolock=nolock):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/contextlib.py\", line 144, in __exit__\n",
      "    next(self.gen)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 750, in external_write_mode\n",
      "    inst.refresh(nolock=True)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1347, in refresh\n",
      "    self.display()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 156, in display\n",
      "    ltext, pbar, rtext = self.container.children\n",
      "                         ^^^^^^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'container'\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1849/362209100.py\", line 40, in <module>\n",
      "    lstm.autofit(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 351, in autofit\n",
      "    study.optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/study.py\", line 490, in optimize\n",
      "    _optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 63, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 160, in _optimize_sequential\n",
      "    frozen_trial_id = _run_trial(study, func, catch)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 234, in _run_trial\n",
      "    _log_failed_trial(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 276, in _log_failed_trial\n",
      "    _logger.warning(\"Trial {} failed with value {}.\".format(trial_number, repr(value_or_values)))\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1551, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 29, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Trial 1 failed with value None.'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 24, in emit\n",
      "    tqdm.write(msg)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 720, in write\n",
      "    with cls.external_write_mode(file=file, nolock=nolock):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/contextlib.py\", line 144, in __exit__\n",
      "    next(self.gen)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 750, in external_write_mode\n",
      "    inst.refresh(nolock=True)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1347, in refresh\n",
      "    self.display()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 156, in display\n",
      "    ltext, pbar, rtext = self.container.children\n",
      "                         ^^^^^^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'container'\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1849/362209100.py\", line 40, in <module>\n",
      "    lstm.autofit(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 351, in autofit\n",
      "    study.optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/study.py\", line 490, in optimize\n",
      "    _optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 63, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 160, in _optimize_sequential\n",
      "    frozen_trial_id = _run_trial(study, func, catch)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 234, in _run_trial\n",
      "    _log_failed_trial(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 269, in _log_failed_trial\n",
      "    _logger.warning(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1551, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 29, in emit\n",
      "    self.handleError(record)\n",
      "Message: \"Trial 2 failed with parameters: {'output_dim': 30, 'LSTMunits': 79, 'learning_rate': 0.0030910901478850747} because of the following error: ImportError('IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html').\"\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 24, in emit\n",
      "    tqdm.write(msg)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 720, in write\n",
      "    with cls.external_write_mode(file=file, nolock=nolock):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/contextlib.py\", line 144, in __exit__\n",
      "    next(self.gen)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 750, in external_write_mode\n",
      "    inst.refresh(nolock=True)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1347, in refresh\n",
      "    self.display()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 156, in display\n",
      "    ltext, pbar, rtext = self.container.children\n",
      "                         ^^^^^^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'container'\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1849/362209100.py\", line 40, in <module>\n",
      "    lstm.autofit(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 351, in autofit\n",
      "    study.optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/study.py\", line 490, in optimize\n",
      "    _optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 63, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 160, in _optimize_sequential\n",
      "    frozen_trial_id = _run_trial(study, func, catch)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 234, in _run_trial\n",
      "    _log_failed_trial(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 276, in _log_failed_trial\n",
      "    _logger.warning(\"Trial {} failed with value {}.\".format(trial_number, repr(value_or_values)))\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1551, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 29, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Trial 2 failed with value None.'\n",
      "Arguments: ()\n",
      "Exception ignored in: <function tqdm.__del__ at 0x7c4296bde980>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1148, in __del__\n",
      "    self.close()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 279, in close\n",
      "    self.disp(bar_style='danger', check_delay=False)\n",
      "    ^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'disp'\n",
      "Exception ignored in: <function tqdm.__del__ at 0x7c4296bde980>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1148, in __del__\n",
      "    self.close()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 279, in close\n",
      "    self.disp(bar_style='danger', check_delay=False)\n",
      "    ^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'disp'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[W 2025-09-12 23:45:23,605] Trial 0 failed with parameters: {'output_dim': 29, 'LSTMunits': 42, 'learning_rate': 0.0003796094420115622} because of the following error: ImportError('IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html').\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 201, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 304, in objective\n",
      "    self.fit(X_train, y_train, X_val, y_val)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 423, in fit\n",
      "    train_dataset = self._convert_to_pytorch_data(X_train, y_train)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 187, in _convert_to_pytorch_data\n",
      "    iterator = tqdm(enumerate(X), desc=\"Converting lists of data to tensordataset\", total=len(X))\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 234, in __init__\n",
      "    self.container = self.status_printer(self.fp, total, self.desc, self.ncols)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 108, in status_printer\n",
      "    raise ImportError(WARN_NOIPYW)\n",
      "ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "[W 2025-09-12 23:45:23,610] Trial 0 failed with value None.\n",
      "[W 2025-09-12 23:45:23,619] Trial 1 failed with parameters: {'output_dim': 15, 'LSTMunits': 39, 'learning_rate': 0.0010747128665878412} because of the following error: ImportError('IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html').\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 201, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 304, in objective\n",
      "    self.fit(X_train, y_train, X_val, y_val)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 423, in fit\n",
      "    train_dataset = self._convert_to_pytorch_data(X_train, y_train)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 187, in _convert_to_pytorch_data\n",
      "    iterator = tqdm(enumerate(X), desc=\"Converting lists of data to tensordataset\", total=len(X))\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 234, in __init__\n",
      "    self.container = self.status_printer(self.fp, total, self.desc, self.ncols)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 108, in status_printer\n",
      "    raise ImportError(WARN_NOIPYW)\n",
      "ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "[W 2025-09-12 23:45:23,626] Trial 1 failed with value None.\n",
      "[W 2025-09-12 23:45:23,638] Trial 2 failed with parameters: {'output_dim': 30, 'LSTMunits': 79, 'learning_rate': 0.0030910901478850747} because of the following error: ImportError('IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html').\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 201, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 304, in objective\n",
      "    self.fit(X_train, y_train, X_val, y_val)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 423, in fit\n",
      "    train_dataset = self._convert_to_pytorch_data(X_train, y_train)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 187, in _convert_to_pytorch_data\n",
      "    iterator = tqdm(enumerate(X), desc=\"Converting lists of data to tensordataset\", total=len(X))\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 234, in __init__\n",
      "    self.container = self.status_printer(self.fp, total, self.desc, self.ncols)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 108, in status_printer\n",
      "    raise ImportError(WARN_NOIPYW)\n",
      "ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "[W 2025-09-12 23:45:23,643] Trial 2 failed with value None.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 24, in emit\n",
      "    tqdm.write(msg)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 720, in write\n",
      "    with cls.external_write_mode(file=file, nolock=nolock):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/contextlib.py\", line 144, in __exit__\n",
      "    next(self.gen)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 750, in external_write_mode\n",
      "    inst.refresh(nolock=True)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1347, in refresh\n",
      "    self.display()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 156, in display\n",
      "    ltext, pbar, rtext = self.container.children\n",
      "                         ^^^^^^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'container'\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1849/362209100.py\", line 40, in <module>\n",
      "    lstm.autofit(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 351, in autofit\n",
      "    study.optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/study.py\", line 490, in optimize\n",
      "    _optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 63, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 160, in _optimize_sequential\n",
      "    frozen_trial_id = _run_trial(study, func, catch)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 234, in _run_trial\n",
      "    _log_failed_trial(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 269, in _log_failed_trial\n",
      "    _logger.warning(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1551, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 29, in emit\n",
      "    self.handleError(record)\n",
      "Message: \"Trial 3 failed with parameters: {'output_dim': 21, 'LSTMunits': 97, 'learning_rate': 0.004524421285451781} because of the following error: ImportError('IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html').\"\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 24, in emit\n",
      "    tqdm.write(msg)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 720, in write\n",
      "    with cls.external_write_mode(file=file, nolock=nolock):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/contextlib.py\", line 144, in __exit__\n",
      "    next(self.gen)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 750, in external_write_mode\n",
      "    inst.refresh(nolock=True)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1347, in refresh\n",
      "    self.display()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 156, in display\n",
      "    ltext, pbar, rtext = self.container.children\n",
      "                         ^^^^^^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'container'\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1849/362209100.py\", line 40, in <module>\n",
      "    lstm.autofit(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 351, in autofit\n",
      "    study.optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/study.py\", line 490, in optimize\n",
      "    _optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 63, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 160, in _optimize_sequential\n",
      "    frozen_trial_id = _run_trial(study, func, catch)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 234, in _run_trial\n",
      "    _log_failed_trial(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 276, in _log_failed_trial\n",
      "    _logger.warning(\"Trial {} failed with value {}.\".format(trial_number, repr(value_or_values)))\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1551, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 29, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Trial 3 failed with value None.'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 24, in emit\n",
      "    tqdm.write(msg)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 720, in write\n",
      "    with cls.external_write_mode(file=file, nolock=nolock):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/contextlib.py\", line 144, in __exit__\n",
      "    next(self.gen)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 750, in external_write_mode\n",
      "    inst.refresh(nolock=True)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1347, in refresh\n",
      "    self.display()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 156, in display\n",
      "    ltext, pbar, rtext = self.container.children\n",
      "                         ^^^^^^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'container'\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1849/362209100.py\", line 40, in <module>\n",
      "    lstm.autofit(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 351, in autofit\n",
      "    study.optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/study.py\", line 490, in optimize\n",
      "    _optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 63, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 160, in _optimize_sequential\n",
      "    frozen_trial_id = _run_trial(study, func, catch)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 234, in _run_trial\n",
      "    _log_failed_trial(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 269, in _log_failed_trial\n",
      "    _logger.warning(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1551, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 29, in emit\n",
      "    self.handleError(record)\n",
      "Message: \"Trial 4 failed with parameters: {'output_dim': 29, 'LSTMunits': 102, 'learning_rate': 0.00013275620634061778} because of the following error: ImportError('IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html').\"\n",
      "Arguments: ()\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[W 2025-09-12 23:45:23,658] Trial 3 failed with parameters: {'output_dim': 21, 'LSTMunits': 97, 'learning_rate': 0.004524421285451781} because of the following error: ImportError('IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html').\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 201, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 304, in objective\n",
      "    self.fit(X_train, y_train, X_val, y_val)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 423, in fit\n",
      "    train_dataset = self._convert_to_pytorch_data(X_train, y_train)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 187, in _convert_to_pytorch_data\n",
      "    iterator = tqdm(enumerate(X), desc=\"Converting lists of data to tensordataset\", total=len(X))\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 234, in __init__\n",
      "    self.container = self.status_printer(self.fp, total, self.desc, self.ncols)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 108, in status_printer\n",
      "    raise ImportError(WARN_NOIPYW)\n",
      "ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "[W 2025-09-12 23:45:23,664] Trial 3 failed with value None.\n",
      "[W 2025-09-12 23:45:23,680] Trial 4 failed with parameters: {'output_dim': 29, 'LSTMunits': 102, 'learning_rate': 0.00013275620634061778} because of the following error: ImportError('IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html').\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 201, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 304, in objective\n",
      "    self.fit(X_train, y_train, X_val, y_val)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 423, in fit\n",
      "    train_dataset = self._convert_to_pytorch_data(X_train, y_train)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 187, in _convert_to_pytorch_data\n",
      "    iterator = tqdm(enumerate(X), desc=\"Converting lists of data to tensordataset\", total=len(X))\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 234, in __init__\n",
      "    self.container = self.status_printer(self.fp, total, self.desc, self.ncols)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 108, in status_printer\n",
      "    raise ImportError(WARN_NOIPYW)\n",
      "ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "[W 2025-09-12 23:45:23,686] Trial 4 failed with value None.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 24, in emit\n",
      "    tqdm.write(msg)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 720, in write\n",
      "    with cls.external_write_mode(file=file, nolock=nolock):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/contextlib.py\", line 144, in __exit__\n",
      "    next(self.gen)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 750, in external_write_mode\n",
      "    inst.refresh(nolock=True)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1347, in refresh\n",
      "    self.display()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 156, in display\n",
      "    ltext, pbar, rtext = self.container.children\n",
      "                         ^^^^^^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'container'\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1849/362209100.py\", line 40, in <module>\n",
      "    lstm.autofit(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 351, in autofit\n",
      "    study.optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/study.py\", line 490, in optimize\n",
      "    _optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 63, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 160, in _optimize_sequential\n",
      "    frozen_trial_id = _run_trial(study, func, catch)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 234, in _run_trial\n",
      "    _log_failed_trial(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 276, in _log_failed_trial\n",
      "    _logger.warning(\"Trial {} failed with value {}.\".format(trial_number, repr(value_or_values)))\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1551, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 29, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Trial 4 failed with value None.'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 24, in emit\n",
      "    tqdm.write(msg)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 720, in write\n",
      "    with cls.external_write_mode(file=file, nolock=nolock):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/contextlib.py\", line 144, in __exit__\n",
      "    next(self.gen)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 750, in external_write_mode\n",
      "    inst.refresh(nolock=True)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1347, in refresh\n",
      "    self.display()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 156, in display\n",
      "    ltext, pbar, rtext = self.container.children\n",
      "                         ^^^^^^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'container'\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1849/362209100.py\", line 40, in <module>\n",
      "    lstm.autofit(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 351, in autofit\n",
      "    study.optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/study.py\", line 490, in optimize\n",
      "    _optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 63, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 160, in _optimize_sequential\n",
      "    frozen_trial_id = _run_trial(study, func, catch)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 234, in _run_trial\n",
      "    _log_failed_trial(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 269, in _log_failed_trial\n",
      "    _logger.warning(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1551, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 29, in emit\n",
      "    self.handleError(record)\n",
      "Message: \"Trial 5 failed with parameters: {'output_dim': 8, 'LSTMunits': 113, 'learning_rate': 0.00033125219830987273} because of the following error: ImportError('IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html').\"\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 24, in emit\n",
      "    tqdm.write(msg)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 720, in write\n",
      "    with cls.external_write_mode(file=file, nolock=nolock):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/contextlib.py\", line 144, in __exit__\n",
      "    next(self.gen)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 750, in external_write_mode\n",
      "    inst.refresh(nolock=True)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1347, in refresh\n",
      "    self.display()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 156, in display\n",
      "    ltext, pbar, rtext = self.container.children\n",
      "                         ^^^^^^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'container'\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1849/362209100.py\", line 40, in <module>\n",
      "    lstm.autofit(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 351, in autofit\n",
      "    study.optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/study.py\", line 490, in optimize\n",
      "    _optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 63, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 160, in _optimize_sequential\n",
      "    frozen_trial_id = _run_trial(study, func, catch)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 234, in _run_trial\n",
      "    _log_failed_trial(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 276, in _log_failed_trial\n",
      "    _logger.warning(\"Trial {} failed with value {}.\".format(trial_number, repr(value_or_values)))\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1551, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 29, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Trial 5 failed with value None.'\n",
      "Arguments: ()\n",
      "--- Logging error ---                         \n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 24, in emit\n",
      "    tqdm.write(msg)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 720, in write\n",
      "    with cls.external_write_mode(file=file, nolock=nolock):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/contextlib.py\", line 144, in __exit__\n",
      "    next(self.gen)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 750, in external_write_mode\n",
      "    inst.refresh(nolock=True)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1347, in refresh\n",
      "    self.display()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 156, in display\n",
      "    ltext, pbar, rtext = self.container.children\n",
      "                         ^^^^^^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'container'\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1849/362209100.py\", line 40, in <module>\n",
      "    lstm.autofit(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 351, in autofit\n",
      "    study.optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/study.py\", line 490, in optimize\n",
      "    _optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 63, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 160, in _optimize_sequential\n",
      "    frozen_trial_id = _run_trial(study, func, catch)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 234, in _run_trial\n",
      "    _log_failed_trial(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 269, in _log_failed_trial\n",
      "    _logger.warning(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1551, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 29, in emit\n",
      "    self.handleError(record)\n",
      "Message: \"Trial 6 failed with parameters: {'output_dim': 12, 'LSTMunits': 48, 'learning_rate': 0.0012615005846664674} because of the following error: ImportError('IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html').\"\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 24, in emit\n",
      "    tqdm.write(msg)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 720, in write\n",
      "    with cls.external_write_mode(file=file, nolock=nolock):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/contextlib.py\", line 144, in __exit__\n",
      "    next(self.gen)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 750, in external_write_mode\n",
      "    inst.refresh(nolock=True)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1347, in refresh\n",
      "    self.display()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 156, in display\n",
      "    ltext, pbar, rtext = self.container.children\n",
      "                         ^^^^^^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'container'\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1849/362209100.py\", line 40, in <module>\n",
      "    lstm.autofit(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 351, in autofit\n",
      "    study.optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/study.py\", line 490, in optimize\n",
      "    _optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 63, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 160, in _optimize_sequential\n",
      "    frozen_trial_id = _run_trial(study, func, catch)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 234, in _run_trial\n",
      "    _log_failed_trial(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 276, in _log_failed_trial\n",
      "    _logger.warning(\"Trial {} failed with value {}.\".format(trial_number, repr(value_or_values)))\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1551, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 29, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Trial 6 failed with value None.'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 24, in emit\n",
      "    tqdm.write(msg)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 720, in write\n",
      "    with cls.external_write_mode(file=file, nolock=nolock):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/contextlib.py\", line 144, in __exit__\n",
      "    next(self.gen)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 750, in external_write_mode\n",
      "    inst.refresh(nolock=True)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1347, in refresh\n",
      "    self.display()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 156, in display\n",
      "    ltext, pbar, rtext = self.container.children\n",
      "                         ^^^^^^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'container'\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1849/362209100.py\", line 40, in <module>\n",
      "    lstm.autofit(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 351, in autofit\n",
      "    study.optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/study.py\", line 490, in optimize\n",
      "    _optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 63, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 160, in _optimize_sequential\n",
      "    frozen_trial_id = _run_trial(study, func, catch)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 234, in _run_trial\n",
      "    _log_failed_trial(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 269, in _log_failed_trial\n",
      "    _logger.warning(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1551, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 29, in emit\n",
      "    self.handleError(record)\n",
      "Message: \"Trial 7 failed with parameters: {'output_dim': 24, 'LSTMunits': 53, 'learning_rate': 0.008805543335070895} because of the following error: ImportError('IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html').\"\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 24, in emit\n",
      "    tqdm.write(msg)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 720, in write\n",
      "    with cls.external_write_mode(file=file, nolock=nolock):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/contextlib.py\", line 144, in __exit__\n",
      "    next(self.gen)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 750, in external_write_mode\n",
      "    inst.refresh(nolock=True)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1347, in refresh\n",
      "    self.display()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 156, in display\n",
      "    ltext, pbar, rtext = self.container.children\n",
      "                         ^^^^^^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'container'\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1849/362209100.py\", line 40, in <module>\n",
      "    lstm.autofit(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 351, in autofit\n",
      "    study.optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/study.py\", line 490, in optimize\n",
      "    _optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 63, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 160, in _optimize_sequential\n",
      "    frozen_trial_id = _run_trial(study, func, catch)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 234, in _run_trial\n",
      "    _log_failed_trial(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 276, in _log_failed_trial\n",
      "    _logger.warning(\"Trial {} failed with value {}.\".format(trial_number, repr(value_or_values)))\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1551, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 29, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Trial 7 failed with value None.'\n",
      "Arguments: ()\n",
      "Exception ignored in: <function tqdm.__del__ at 0x7c4296bde980>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1148, in __del__\n",
      "    self.close()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 279, in close\n",
      "    self.disp(bar_style='danger', check_delay=False)\n",
      "    ^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'disp'\n",
      "Exception ignored in: <function tqdm.__del__ at 0x7c4296bde980>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1148, in __del__\n",
      "    self.close()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 279, in close\n",
      "    self.disp(bar_style='danger', check_delay=False)\n",
      "    ^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'disp'\n",
      "Exception ignored in: <function tqdm.__del__ at 0x7c4296bde980>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1148, in __del__\n",
      "    self.close()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 279, in close\n",
      "    self.disp(bar_style='danger', check_delay=False)\n",
      "    ^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'disp'\n",
      "Exception ignored in: <function tqdm.__del__ at 0x7c4296bde980>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1148, in __del__\n",
      "    self.close()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 279, in close\n",
      "    self.disp(bar_style='danger', check_delay=False)\n",
      "    ^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'disp'\n",
      "Exception ignored in: <function tqdm.__del__ at 0x7c4296bde980>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1148, in __del__\n",
      "    self.close()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 279, in close\n",
      "    self.disp(bar_style='danger', check_delay=False)\n",
      "    ^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'disp'\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 24, in emit\n",
      "    tqdm.write(msg)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 720, in write\n",
      "    with cls.external_write_mode(file=file, nolock=nolock):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/contextlib.py\", line 144, in __exit__\n",
      "    next(self.gen)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 750, in external_write_mode\n",
      "    inst.refresh(nolock=True)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1347, in refresh\n",
      "    self.display()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 156, in display\n",
      "    ltext, pbar, rtext = self.container.children\n",
      "                         ^^^^^^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'container'\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1849/362209100.py\", line 40, in <module>\n",
      "    lstm.autofit(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 351, in autofit\n",
      "    study.optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/study.py\", line 490, in optimize\n",
      "    _optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 63, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 160, in _optimize_sequential\n",
      "    frozen_trial_id = _run_trial(study, func, catch)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 234, in _run_trial\n",
      "    _log_failed_trial(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 269, in _log_failed_trial\n",
      "    _logger.warning(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1551, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 29, in emit\n",
      "    self.handleError(record)\n",
      "Message: \"Trial 8 failed with parameters: {'output_dim': 10, 'LSTMunits': 47, 'learning_rate': 0.009811161923633205} because of the following error: ImportError('IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html').\"\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 24, in emit\n",
      "    tqdm.write(msg)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 720, in write\n",
      "    with cls.external_write_mode(file=file, nolock=nolock):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/contextlib.py\", line 144, in __exit__\n",
      "    next(self.gen)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 750, in external_write_mode\n",
      "    inst.refresh(nolock=True)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1347, in refresh\n",
      "    self.display()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 156, in display\n",
      "    ltext, pbar, rtext = self.container.children\n",
      "                         ^^^^^^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'container'\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1849/362209100.py\", line 40, in <module>\n",
      "    lstm.autofit(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 351, in autofit\n",
      "    study.optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/study.py\", line 490, in optimize\n",
      "    _optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 63, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 160, in _optimize_sequential\n",
      "    frozen_trial_id = _run_trial(study, func, catch)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 234, in _run_trial\n",
      "    _log_failed_trial(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 276, in _log_failed_trial\n",
      "    _logger.warning(\"Trial {} failed with value {}.\".format(trial_number, repr(value_or_values)))\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1551, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 29, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Trial 8 failed with value None.'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 24, in emit\n",
      "    tqdm.write(msg)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 720, in write\n",
      "    with cls.external_write_mode(file=file, nolock=nolock):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/contextlib.py\", line 144, in __exit__\n",
      "    next(self.gen)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 750, in external_write_mode\n",
      "    inst.refresh(nolock=True)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1347, in refresh\n",
      "    self.display()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 156, in display\n",
      "    ltext, pbar, rtext = self.container.children\n",
      "                         ^^^^^^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'container'\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1849/362209100.py\", line 40, in <module>\n",
      "    lstm.autofit(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 351, in autofit\n",
      "    study.optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/study.py\", line 490, in optimize\n",
      "    _optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 63, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 160, in _optimize_sequential\n",
      "    frozen_trial_id = _run_trial(study, func, catch)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 234, in _run_trial\n",
      "    _log_failed_trial(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 269, in _log_failed_trial\n",
      "    _logger.warning(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1551, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 29, in emit\n",
      "    self.handleError(record)\n",
      "Message: \"Trial 9 failed with parameters: {'output_dim': 31, 'LSTMunits': 93, 'learning_rate': 0.0033369990400079937} because of the following error: ImportError('IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html').\"\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 24, in emit\n",
      "    tqdm.write(msg)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 720, in write\n",
      "    with cls.external_write_mode(file=file, nolock=nolock):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/contextlib.py\", line 144, in __exit__\n",
      "    next(self.gen)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 750, in external_write_mode\n",
      "    inst.refresh(nolock=True)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1347, in refresh\n",
      "    self.display()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 156, in display\n",
      "    ltext, pbar, rtext = self.container.children\n",
      "                         ^^^^^^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'container'\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 638, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py\", line 1971, in _run_once\n",
      "    handle._run()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/codespace/.local/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_1849/362209100.py\", line 40, in <module>\n",
      "    lstm.autofit(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 351, in autofit\n",
      "    study.optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/study.py\", line 490, in optimize\n",
      "    _optimize(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 63, in _optimize\n",
      "    _optimize_sequential(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 160, in _optimize_sequential\n",
      "    frozen_trial_id = _run_trial(study, func, catch)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 234, in _run_trial\n",
      "    _log_failed_trial(\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 276, in _log_failed_trial\n",
      "    _logger.warning(\"Trial {} failed with value {}.\".format(trial_number, repr(value_or_values)))\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1551, in warning\n",
      "    self._log(WARNING, msg, args, **kwargs)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1684, in _log\n",
      "    self.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1700, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1762, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/logging/__init__.py\", line 1028, in handle\n",
      "    self.emit(record)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/progress_bar.py\", line 29, in emit\n",
      "    self.handleError(record)\n",
      "Message: 'Trial 9 failed with value None.'\n",
      "Arguments: ()\n",
      "100%|██████████| 10/10 [00:00<00:00, 52.24it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[W 2025-09-12 23:45:23,699] Trial 5 failed with parameters: {'output_dim': 8, 'LSTMunits': 113, 'learning_rate': 0.00033125219830987273} because of the following error: ImportError('IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html').\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 201, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 304, in objective\n",
      "    self.fit(X_train, y_train, X_val, y_val)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 423, in fit\n",
      "    train_dataset = self._convert_to_pytorch_data(X_train, y_train)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 187, in _convert_to_pytorch_data\n",
      "    iterator = tqdm(enumerate(X), desc=\"Converting lists of data to tensordataset\", total=len(X))\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 234, in __init__\n",
      "    self.container = self.status_printer(self.fp, total, self.desc, self.ncols)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 108, in status_printer\n",
      "    raise ImportError(WARN_NOIPYW)\n",
      "ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "[W 2025-09-12 23:45:23,704] Trial 5 failed with value None.\n",
      "[W 2025-09-12 23:45:23,717] Trial 6 failed with parameters: {'output_dim': 12, 'LSTMunits': 48, 'learning_rate': 0.0012615005846664674} because of the following error: ImportError('IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html').\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 201, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 304, in objective\n",
      "    self.fit(X_train, y_train, X_val, y_val)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 423, in fit\n",
      "    train_dataset = self._convert_to_pytorch_data(X_train, y_train)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 187, in _convert_to_pytorch_data\n",
      "    iterator = tqdm(enumerate(X), desc=\"Converting lists of data to tensordataset\", total=len(X))\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 234, in __init__\n",
      "    self.container = self.status_printer(self.fp, total, self.desc, self.ncols)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 108, in status_printer\n",
      "    raise ImportError(WARN_NOIPYW)\n",
      "ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "[W 2025-09-12 23:45:23,722] Trial 6 failed with value None.\n",
      "[W 2025-09-12 23:45:23,730] Trial 7 failed with parameters: {'output_dim': 24, 'LSTMunits': 53, 'learning_rate': 0.008805543335070895} because of the following error: ImportError('IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html').\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 201, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 304, in objective\n",
      "    self.fit(X_train, y_train, X_val, y_val)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 423, in fit\n",
      "    train_dataset = self._convert_to_pytorch_data(X_train, y_train)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 187, in _convert_to_pytorch_data\n",
      "    iterator = tqdm(enumerate(X), desc=\"Converting lists of data to tensordataset\", total=len(X))\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 234, in __init__\n",
      "    self.container = self.status_printer(self.fp, total, self.desc, self.ncols)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 108, in status_printer\n",
      "    raise ImportError(WARN_NOIPYW)\n",
      "ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "[W 2025-09-12 23:45:23,736] Trial 7 failed with value None.\n",
      "[W 2025-09-12 23:45:23,753] Trial 8 failed with parameters: {'output_dim': 10, 'LSTMunits': 47, 'learning_rate': 0.009811161923633205} because of the following error: ImportError('IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html').\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 201, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 304, in objective\n",
      "    self.fit(X_train, y_train, X_val, y_val)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 423, in fit\n",
      "    train_dataset = self._convert_to_pytorch_data(X_train, y_train)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 187, in _convert_to_pytorch_data\n",
      "    iterator = tqdm(enumerate(X), desc=\"Converting lists of data to tensordataset\", total=len(X))\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 234, in __init__\n",
      "    self.container = self.status_printer(self.fp, total, self.desc, self.ncols)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 108, in status_printer\n",
      "    raise ImportError(WARN_NOIPYW)\n",
      "ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "[W 2025-09-12 23:45:23,763] Trial 8 failed with value None.\n",
      "[W 2025-09-12 23:45:23,778] Trial 9 failed with parameters: {'output_dim': 31, 'LSTMunits': 93, 'learning_rate': 0.0033369990400079937} because of the following error: ImportError('IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html').\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/optuna/study/_optimize.py\", line 201, in _run_trial\n",
      "    value_or_values = func(trial)\n",
      "                      ^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 304, in objective\n",
      "    self.fit(X_train, y_train, X_val, y_val)\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 423, in fit\n",
      "    train_dataset = self._convert_to_pytorch_data(X_train, y_train)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py\", line 187, in _convert_to_pytorch_data\n",
      "    iterator = tqdm(enumerate(X), desc=\"Converting lists of data to tensordataset\", total=len(X))\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 234, in __init__\n",
      "    self.container = self.status_printer(self.fp, total, self.desc, self.ncols)\n",
      "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 108, in status_printer\n",
      "    raise ImportError(WARN_NOIPYW)\n",
      "ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "[W 2025-09-12 23:45:23,785] Trial 9 failed with value None.\n",
      "Model training complete!\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "# Install dependencies\n",
    "%pip install torch_molecule tqdm\n",
    "\n",
    "# Import libraries\n",
    "from tqdm.notebook import tqdm as notebook_tqdm\n",
    "import tqdm\n",
    "tqdm.tqdm = notebook_tqdm\n",
    "tqdm.trange = notebook_tqdm\n",
    "\n",
    "from torch_molecule import LSTMMolecularPredictor\n",
    "from torch_molecule.utils.search import ParameterType, ParameterSpec\n",
    "import pandas as pd\n",
    "\n",
    "# Define search parameters for hyperparameter tuning\n",
    "search_parameters = {\n",
    "    \"output_dim\": ParameterSpec(ParameterType.INTEGER, (8, 32)),\n",
    "    \"LSTMunits\": ParameterSpec(ParameterType.INTEGER, (30, 120)),\n",
    "    \"learning_rate\": ParameterSpec(ParameterType.LOG_FLOAT, (1e-4, 1e-2)),\n",
    "}\n",
    "\n",
    "# Initialize LSTM model for regression with 5 targets\n",
    "lstm = LSTMMolecularPredictor(\n",
    "    task_type=\"regression\",\n",
    "    num_task=5,\n",
    "    batch_size=192,\n",
    "    epochs=200,\n",
    "    verbose=True\n",
    ")\n",
    "\n",
    "print(\"Model initialized successfully\")\n",
    "\n",
    "# Prepare training and validation data\n",
    "X_train = dev_train['SMILES'].to_list()\n",
    "y_train = dev_train[['Tg', 'FFV', 'Tc', 'Density', 'Rg']].to_numpy()\n",
    "\n",
    "X_val = dev_val['SMILES'].to_list()\n",
    "y_val = dev_val[['Tg', 'FFV', 'Tc', 'Density', 'Rg']].to_numpy()\n",
    "\n",
    "# Train the model with hyperparameter search\n",
    "lstm.autofit(\n",
    "    X_train=X_train,\n",
    "    y_train=y_train,\n",
    "    X_val=X_val,\n",
    "    y_val=y_val,\n",
    "    search_parameters=search_parameters,\n",
    "    n_trials=10  # number of hyperparameter search trials\n",
    ")\n",
    "\n",
    "print(\"Model training complete!\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "af422a5c",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function tqdm.__del__ at 0x7c4296bde980>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1148, in __del__\n",
      "    self.close()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 279, in close\n",
      "    self.disp(bar_style='danger', check_delay=False)\n",
      "    ^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'disp'\n",
      "Exception ignored in: <function tqdm.__del__ at 0x7c4296bde980>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1148, in __del__\n",
      "    self.close()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 279, in close\n",
      "    self.disp(bar_style='danger', check_delay=False)\n",
      "    ^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'disp'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Sample submission:\n",
      "           id  Tg  FFV  Tc  Density  Rg\n",
      "0  1109053969   0    0   0        0   0\n",
      "1  1422188626   0    0   0        0   0\n",
      "2  2032016830   0    0   0        0   0\n",
      "Test set:\n",
      "           id                                             SMILES\n",
      "0  1109053969  *Oc1ccc(C=NN=Cc2ccc(Oc3ccc(C(c4ccc(*)cc4)(C(F)...\n",
      "1  1422188626  *Oc1ccc(C(C)(C)c2ccc(Oc3ccc(C(=O)c4cccc(C(=O)c...\n",
      "2  2032016830  *c1cccc(OCCCCCCCCOc2cccc(N3C(=O)c4ccc(-c5cccc6...\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "This model is not fitted yet. Call 'fit' before using it.",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mAttributeError\u001b[39m                            Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[16]\u001b[39m\u001b[32m, line 14\u001b[39m\n\u001b[32m     11\u001b[39m X_test = ts_test[\u001b[33m'\u001b[39m\u001b[33mSMILES\u001b[39m\u001b[33m'\u001b[39m].to_list()\n\u001b[32m     13\u001b[39m \u001b[38;5;66;03m# Predict using the trained LSTM model\u001b[39;00m\n\u001b[32m---> \u001b[39m\u001b[32m14\u001b[39m lstm_preds = \u001b[43mlstm\u001b[49m\u001b[43m.\u001b[49m\u001b[43mpredict\u001b[49m\u001b[43m(\u001b[49m\u001b[43mX_test\u001b[49m\u001b[43m)\u001b[49m  \u001b[38;5;66;03m# Returns a NumPy array (num_samples, 5)\u001b[39;00m\n\u001b[32m     16\u001b[39m \u001b[38;5;66;03m# Build the submission DataFrame\u001b[39;00m\n\u001b[32m     17\u001b[39m submission_df = sample_sub.copy()\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py:521\u001b[39m, in \u001b[36mLSTMMolecularPredictor.predict\u001b[39m\u001b[34m(self, X)\u001b[39m\n\u001b[32m    506\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mpredict\u001b[39m(\u001b[38;5;28mself\u001b[39m, X: List[\u001b[38;5;28mstr\u001b[39m]) -> Dict[\u001b[38;5;28mstr\u001b[39m, np.ndarray]:\n\u001b[32m    507\u001b[39m \u001b[38;5;250m    \u001b[39m\u001b[33;03m\"\"\"Make predictions using the fitted model.\u001b[39;00m\n\u001b[32m    508\u001b[39m \n\u001b[32m    509\u001b[39m \u001b[33;03m    Parameters\u001b[39;00m\n\u001b[32m   (...)\u001b[39m\u001b[32m    519\u001b[39m \n\u001b[32m    520\u001b[39m \u001b[33;03m    \"\"\"\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m521\u001b[39m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_check_is_fitted\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    523\u001b[39m     \u001b[38;5;66;03m# Convert to token format and create loader\u001b[39;00m\n\u001b[32m    524\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(X, \u001b[38;5;28mlist\u001b[39m) \u001b[38;5;129;01mor\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mall\u001b[39m(\u001b[38;5;28misinstance\u001b[39m(item, \u001b[38;5;28mstr\u001b[39m) \u001b[38;5;28;01mfor\u001b[39;00m item \u001b[38;5;129;01min\u001b[39;00m X):\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/base/base.py:348\u001b[39m, in \u001b[36mBaseModel._check_is_fitted\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    340\u001b[39m \u001b[38;5;250m\u001b[39m\u001b[33;03m\"\"\"Check if the model is fitted.\u001b[39;00m\n\u001b[32m    341\u001b[39m \u001b[33;03m\u001b[39;00m\n\u001b[32m    342\u001b[39m \u001b[33;03mRaises\u001b[39;00m\n\u001b[32m   (...)\u001b[39m\u001b[32m    345\u001b[39m \u001b[33;03m    If the model is not fitted\u001b[39;00m\n\u001b[32m    346\u001b[39m \u001b[33;03m\"\"\"\u001b[39;00m\n\u001b[32m    347\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m.is_fitted_:\n\u001b[32m--> \u001b[39m\u001b[32m348\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mAttributeError\u001b[39;00m(\u001b[33m\"\u001b[39m\u001b[33mThis model is not fitted yet. Call \u001b[39m\u001b[33m'\u001b[39m\u001b[33mfit\u001b[39m\u001b[33m'\u001b[39m\u001b[33m before using it.\u001b[39m\u001b[33m\"\u001b[39m)\n",
      "\u001b[31mAttributeError\u001b[39m: This model is not fitted yet. Call 'fit' before using it."
     ]
    }
   ],
   "source": [
    "# Load sample submission and test set\n",
    "sample_sub = ss.copy()\n",
    "ts_test = ts.copy()\n",
    "\n",
    "print(\"Sample submission:\")\n",
    "print(sample_sub.head())\n",
    "print(\"Test set:\")\n",
    "print(ts_test.head())\n",
    "\n",
    "# Prepare test SMILES list\n",
    "X_test = ts_test['SMILES'].to_list()\n",
    "\n",
    "# Predict using the trained LSTM model\n",
    "lstm_preds = lstm.predict(X_test)  # Returns a NumPy array (num_samples, 5)\n",
    "\n",
    "# Build the submission DataFrame\n",
    "submission_df = sample_sub.copy()\n",
    "submission_df[['Tg', 'FFV', 'Tc', 'Density', 'Rg']] = lstm_preds\n",
    "\n",
    "print(\"Submission DataFrame:\")\n",
    "print(submission_df.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "95603303",
   "metadata": {},
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "This model is not fitted yet. Call 'fit' before using it.",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mAttributeError\u001b[39m                            Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[19]\u001b[39m\u001b[32m, line 5\u001b[39m\n\u001b[32m      2\u001b[39m X_test = ts[\u001b[33m'\u001b[39m\u001b[33mSMILES\u001b[39m\u001b[33m'\u001b[39m].astype(\u001b[38;5;28mstr\u001b[39m).to_list()\n\u001b[32m      4\u001b[39m \u001b[38;5;66;03m# Predict using the trained LSTM model\u001b[39;00m\n\u001b[32m----> \u001b[39m\u001b[32m5\u001b[39m preds_dict = \u001b[43mlstm\u001b[49m\u001b[43m.\u001b[49m\u001b[43mpredict\u001b[49m\u001b[43m(\u001b[49m\u001b[43mX_test\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m      6\u001b[39m lstm_preds = preds_dict[\u001b[33m'\u001b[39m\u001b[33mprediction\u001b[39m\u001b[33m'\u001b[39m]  \u001b[38;5;66;03m# NumPy array of shape (num_samples, 5)\u001b[39;00m\n\u001b[32m      8\u001b[39m \u001b[38;5;66;03m# Build the submission DataFrame\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/predictor/lstm/modeling_lstm.py:521\u001b[39m, in \u001b[36mLSTMMolecularPredictor.predict\u001b[39m\u001b[34m(self, X)\u001b[39m\n\u001b[32m    506\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mpredict\u001b[39m(\u001b[38;5;28mself\u001b[39m, X: List[\u001b[38;5;28mstr\u001b[39m]) -> Dict[\u001b[38;5;28mstr\u001b[39m, np.ndarray]:\n\u001b[32m    507\u001b[39m \u001b[38;5;250m    \u001b[39m\u001b[33;03m\"\"\"Make predictions using the fitted model.\u001b[39;00m\n\u001b[32m    508\u001b[39m \n\u001b[32m    509\u001b[39m \u001b[33;03m    Parameters\u001b[39;00m\n\u001b[32m   (...)\u001b[39m\u001b[32m    519\u001b[39m \n\u001b[32m    520\u001b[39m \u001b[33;03m    \"\"\"\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m521\u001b[39m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_check_is_fitted\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    523\u001b[39m     \u001b[38;5;66;03m# Convert to token format and create loader\u001b[39;00m\n\u001b[32m    524\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(X, \u001b[38;5;28mlist\u001b[39m) \u001b[38;5;129;01mor\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mall\u001b[39m(\u001b[38;5;28misinstance\u001b[39m(item, \u001b[38;5;28mstr\u001b[39m) \u001b[38;5;28;01mfor\u001b[39;00m item \u001b[38;5;129;01min\u001b[39;00m X):\n",
      "\u001b[36mFile \u001b[39m\u001b[32m/usr/local/python/3.12.1/lib/python3.12/site-packages/torch_molecule/base/base.py:348\u001b[39m, in \u001b[36mBaseModel._check_is_fitted\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    340\u001b[39m \u001b[38;5;250m\u001b[39m\u001b[33;03m\"\"\"Check if the model is fitted.\u001b[39;00m\n\u001b[32m    341\u001b[39m \u001b[33;03m\u001b[39;00m\n\u001b[32m    342\u001b[39m \u001b[33;03mRaises\u001b[39;00m\n\u001b[32m   (...)\u001b[39m\u001b[32m    345\u001b[39m \u001b[33;03m    If the model is not fitted\u001b[39;00m\n\u001b[32m    346\u001b[39m \u001b[33;03m\"\"\"\u001b[39;00m\n\u001b[32m    347\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m.is_fitted_:\n\u001b[32m--> \u001b[39m\u001b[32m348\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mAttributeError\u001b[39;00m(\u001b[33m\"\u001b[39m\u001b[33mThis model is not fitted yet. Call \u001b[39m\u001b[33m'\u001b[39m\u001b[33mfit\u001b[39m\u001b[33m'\u001b[39m\u001b[33m before using it.\u001b[39m\u001b[33m\"\u001b[39m)\n",
      "\u001b[31mAttributeError\u001b[39m: This model is not fitted yet. Call 'fit' before using it."
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function tqdm.__del__ at 0x7c4296bde980>\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/std.py\", line 1148, in __del__\n",
      "    self.close()\n",
      "  File \"/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/notebook.py\", line 279, in close\n",
      "    self.disp(bar_style='danger', check_delay=False)\n",
      "    ^^^^^^^^^\n",
      "AttributeError: 'tqdm_notebook' object has no attribute 'disp'\n"
     ]
    }
   ],
   "source": [
    "# Ensure test SMILES are strings\n",
    "X_test = ts['SMILES'].astype(str).to_list()\n",
    "\n",
    "# Predict using the trained LSTM model\n",
    "preds_dict = lstm.predict(X_test)\n",
    "lstm_preds = preds_dict['prediction']  # NumPy array of shape (num_samples, 5)\n",
    "\n",
    "# Build the submission DataFrame\n",
    "submission_df = ss.copy()\n",
    "submission_df[['Tg', 'FFV', 'Tc', 'Density', 'Rg']] = lstm_preds\n",
    "\n",
    "# Preview predictions\n",
    "print(submission_df.head())\n",
    "\n",
    "# Save predictions to CSV\n",
    "submission_df.to_csv('submission.csv', index=False)\n",
    "print(\"Predictions for test set saved as submission.csv\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f046b672",
   "metadata": {},
   "outputs": [],
   "source": [
    "# save to CSV\n",
    "submission_df.to_csv('submission.csv', index=False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
